stages:
  preprocess:
    cmd: python src/preprocess.py data/train.csv data/clean_train.csv
    deps:
      - src/preprocess.py
      - data/train.csv
    outs:
      - data/clean_train.csv
    params:
      - train.test_size
      - train.random_state

  train:
    cmd: python src/train.py data/clean_train.csv models/model.pkl
    deps:
      - src/train.py
      - data/clean_train.csv
    outs:
      - models/model.pkl
    params:
      - train.n_estimators
      - train.random_state
      - train.test_size
